### ISSUE TITLE
Can only collect 47 posts

### ISSUE THREAD

**Issue by gauthier-bonnot** [midnightSuyama/instagram-explore#2]
Hello there,

First off, thanks for the program, it is doing exactly what I want.
The only problem I am facing is that I could only collect a maximum of 47 posts, for some reason it doesn't grab more than that...

Is there anything in the code I could change to collect more?

**Comment by midnightSuyama** [comment]
Do you use `sleep` ?

Example:
```
import instagram_explore as ie
import time

data, cursor = ie.user('instagram')
for i in range(48):
    data, cursor = ie.user('instagram', cursor)
    time.sleep(1)
```

**Comment by gauthier-bonnot** [comment]
Thanks a lot for the quick reply !
I just looked up time and sleep for python, and went through your test folder also, I hadn't noticed it the first time.

As you could probably guess, I am a beginner in Python. For a class project I would like to collect Instagram data from a particular tag in order to analyze them and highlight the ongoing discussions.

The tag I'm searching is #ironmantraining, basically I wrote this upon your examples:

```
import instagram_explore as ie
import time

res = ie.tag('ironmantraining')
for i in range(48) :
    data, cursor = ie.tag('ironmantraining')
    time.sleep(1)
print(res.data)
```

When running it, it gets the top posts, and a couple of recent ones. I am assuming it fails at refreshing the page and load more pictures.
It would be great if you could point me in the right direction.

Thanks again :-)

**Comment by midnightSuyama** [comment]
OK, understood.

Please try:

```
import instagram_explore as ie
import time

data, cursor = ie.tag('ironmantraining')
print(data)

# 12 posts in loop once
for i in range(3):
    data, cursor = ie.tag('ironmantraining', cursor)
    print(data)
    time.sleep(1)
```

**Comment by gauthier-bonnot** [comment]
Brilliant, it works like a charm !
Thank you, I will reference you in my research work.

Cheers :-)
